blueprint:
  name: "Gruppen-Thermostat-Zeitplan mit zwei Temperaturstufen"
  domain: automation

  input:
    thermostat_entities:
      name: "Thermostate"
      selector:
        entity:
          domain: climate
          multiple: true

    time_day:
      name: "Uhrzeit Tag"
      selector:
        time: {}

    time_night:
      name: "Uhrzeit Nacht"
      selector:
        time: {}

    helper_day_temp:
      name: "Tagestemperatur Helfer"
      selector:
        entity:
          domain: input_number

    helper_night_temp:
      name: "Nachttemperatur Helfer"
      selector:
        entity:
          domain: input_number

    summer_mode_helper:
      name: "Sommermodus"
      selector:
        entity:
          domain: input_boolean

mode: single

trigger:
  - platform: time
    at: !input time_day
    id: day
  - platform: time
    at: !input time_night
    id: night

condition:
  - condition: state
    entity_id: !input summer_mode_helper
    state: "off"

action:

  # 👉 HIER Blueprint Inputs in echte Variablen wandeln
  - variables:
      day_entity: !input helper_day_temp
      night_entity: !input helper_night_temp

  - choose:

      - conditions:
          - condition: trigger
            id: day
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat_entities
            data:
              temperature: "{{ states(day_entity) | float }}"

      - conditions:
          - condition: trigger
            id: night
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat_entities
            data:
              temperature: "{{ states(night_entity) | float }}"
