blueprint:
  name: "Gruppen-Thermostat-Zeitplan mit zwei Temperaturstufen"
  description: >
    Steuert mehrere Thermostate mit zwei Temperaturstufen (z. B. Tag/Nacht).
  domain: automation
  input:
    thermostat_entities:
      name: "Thermostate"
      selector:
        entity:
          domain: climate
          multiple: true
    time_day:
      name: "Uhrzeit für Tagesmodus"
      selector:
        time: {}
    time_night:
      name: "Uhrzeit für Nachtmodus"
      selector:
        time: {}
    helper_day_temp:
      name: "Helfer für Tagestemperatur"
      selector:
        entity:
          domain: input_number
    helper_night_temp:
      name: "Helfer für Nachttemperatur"
      selector:
        entity:
          domain: input_number

# WICHTIG: Inputs für Templates in Variablen überführen
variables:
  day_helper: !input helper_day_temp
  night_helper: !input helper_night_temp

mode: single

trigger:
  - platform: time
    at: !input time_day
    id: "day"
  - platform: time
    at: !input time_night
    id: "night"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "day"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat_entities
            data:
              # Hier nutzen wir nun die oben definierte Variable
              temperature: "{{ states(day_helper) | float(21) }}"
      - conditions:
          - condition: trigger
            id: "night"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat_entities
            data:
              temperature: "{{ states(night_helper) | float(18) }}"
