blueprint:
  name: "Gruppen-Thermostat-Zeitplan mit zwei Temperaturstufen"
  domain: automation
  input:
    thermostat_entities:
      name: "Thermostate (mehrere auswählbar)"
      selector:
        entity:
          domain: climate
          multiple: true
    time_day:
      name: "Uhrzeit für Tagesmodus"
      selector:
        time: {}
    time_night:
      name: "Uhrzeit für Nachtmodus"
      selector:
        time: {}
    helper_day_temp:
      name: "Helfer für Tagestemperatur"
      selector:
        entity:
          domain: input_number
    helper_night_temp:
      name: "Helfer für Nachttemperatur"
      selector:
        entity:
          domain: input_number
    summer_mode_helper:
      name: "Sommermodus"
      selector:
        entity:
          domain: input_boolean

mode: single

trigger:
  - platform: time
    at: !input time_day
    id: day
  - platform: time
    at: !input time_night
    id: night

condition:
  - condition: state
    entity_id: !input summer_mode_helper
    state: "off"

action:
  - variables:
      day_helper: !input helper_day_temp
      night_helper: !input helper_night_temp
      day_temp: "{{ states(day_helper) | float }}"
      night_temp: "{{ states(night_helper) | float }}"

  - choose:
      - conditions:
          - condition: trigger
            id: day
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat_entities
            data:
              temperature: "{{ day_temp }}"

      - conditions:
          - condition: trigger
            id: night
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat_entities
            data:
              temperature: "{{ night_temp }}"
