blueprint:
  name: "Gruppen-Thermostat-Zeitplan mit zwei Temperaturstufen"
  description: >
    Steuert mehrere Thermostate mit zwei Temperaturstufen (z. B. Tag/Nacht) zu festgelegten Uhrzeiten.
    Die Temperaturen werden per Helfer eingestellt – perfekt für Räume mit gleicher Temperatur.
  domain: automation
  input:
    thermostat_entities:
      name: "Thermostate (mehrere auswählbar)"
      selector:
        entity:
          domain: climate
          multiple: true
    time_day:
      name: "Uhrzeit für Tagesmodus"
      selector:
        time: {}
    time_night:
      name: "Uhrzeit für Nachtmodus"
      selector:
        time: {}
    helper_day_temp:
      name: "Helfer für Tagestemperatur"
      selector:
        entity:
          domain: input_number
    helper_night_temp:
      name: "Helfer für Nachttemperatur"
      selector:
        entity:
          domain: input_number

mode: single

trigger:
  - platform: time
    at: !input time_day
    id: day
  - platform: time
    at: !input time_night
    id: night

action:
  - variables:
      day_temp: "{{ states(!input helper_day_temp) | float }}"
      night_temp: "{{ states(!input helper_night_temp) | float }}"

  - choose:
      - conditions:
          - condition: trigger
            id: day
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat_entities
            data:
              temperature: "{{ day_temp }}"

      - conditions:
          - condition: trigger
            id: night
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat_entities
            data:
              temperature: "{{ night_temp }}"
