blueprint:
  name: Gruppen-Thermostat-Zeitplan
  domain: automation

  input:
    thermostat_entities:
      selector:
        entity:
          domain: climate
          multiple: true

    time_day:
      selector:
        time: {}

    time_night:
      selector:
        time: {}

    helper_day_temp:
      selector:
        entity:
          domain: input_number

    helper_night_temp:
      selector:
        entity:
          domain: input_number

    summer_mode_helper:
      selector:
        entity:
          domain: input_boolean

mode: single

trigger:
  - platform: time
    at: !input time_day
    id: day
  - platform: time
    at: !input time_night
    id: night

condition:
  - condition: state
    entity_id: !input summer_mode_helper
    state: "off"

action:

  - variables:
      day_entity: !input helper_day_temp
      night_entity: !input helper_night_temp
      target_temp: 0

  - choose:

      - conditions:
          - condition: trigger
            id: day
        sequence:
          - variables:
              target_temp: "{{ states(day_entity) | float }}"

      - conditions:
          - condition: trigger
            id: night
        sequence:
          - variables:
              target_temp: "{{ states(night_entity) | float }}"

  # 👉 Service erst NACH choose!
  - service: climate.set_temperature
    target:
      entity_id: !input thermostat_entities
    data:
      temperature: "{{ target_temp }}"
