blueprint:
  name: Gruppen-Thermostat-Zeitplan
  domain: automation

  input:
    thermostat_entities:
      selector:
        entity:
          domain: climate
          multiple: true

    time_day:
      selector:
        time: {}

    time_night:
      selector:
        time: {}

    helper_day_temp:
      selector:
        entity:
          domain: input_number

    helper_night_temp:
      selector:
        entity:
          domain: input_number

    summer_mode_helper:
      selector:
        entity:
          domain: input_boolean

mode: single

trigger:
  - platform: time
    at: !input time_day
    id: day
  - platform: time
    at: !input time_night
    id: night

condition:
  - condition: state
    entity_id: !input summer_mode_helper
    state: "off"

action:
  - variables:
      # Temperatur aus Helfern auslesen
      day_temp: "{{ states(!input helper_day_temp) | float }}"
      night_temp: "{{ states(!input helper_night_temp) | float }}"
      target_temp: >
        {% if trigger.id == 'day' %}
          {{ day_temp }}
        {% else %}
          {{ night_temp }}
        {% endif %}

  # EIN Service Call außerhalb von choose
  - service: climate.set_temperature
    target:
      entity_id: !input thermostat_entities
    data:
      temperature: "{{ target_temp }}"
